# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: events.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65vents.proto\x12\x04tvos\"\xa3\x02\n\x0c\x45ventPayload\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x03\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x14\n\x0ctext_payload\x18\x04 \x01(\t\x12\x30\n\x07metrics\x18\x05 \x03(\x0b\x32\x1f.tvos.EventPayload.MetricsEntry\x12\x32\n\x08metadata\x18\x06 \x03(\x0b\x32 .tvos.EventPayload.MetadataEntry\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTPAYLOAD_METRICSENTRY']._loaded_options = None
  _globals['_EVENTPAYLOAD_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_EVENTPAYLOAD_METADATAENTRY']._loaded_options = None
  _globals['_EVENTPAYLOAD_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_EVENTPAYLOAD']._serialized_start=23
  _globals['_EVENTPAYLOAD']._serialized_end=314
  _globals['_EVENTPAYLOAD_METRICSENTRY']._serialized_start=219
  _globals['_EVENTPAYLOAD_METRICSENTRY']._serialized_end=265
  _globals['_EVENTPAYLOAD_METADATAENTRY']._serialized_start=267
  _globals['_EVENTPAYLOAD_METADATAENTRY']._serialized_end=314
# @@protoc_insertion_point(module_scope)
